### ISSUE TITLE
[FEATURE] Dark mode

### ISSUE THREAD

**Issue by JeremiahPinto** [codersforcauses/p2s-frontend#21]
**Is your feature request related to a problem? Please describe.**
The ability to change between light and dark themes.

**Describe the solution you'd like**
On the click of a button, the theme of the entire website and it's components should change between light and dark modes. The preferred theme should be saved for use on all/current device(s) for a long time.

**Comment by DrewAlexander98** [comment]
Is this the same as the “Colour theme” issue?

**Comment by JeremiahPinto** [comment]
Not really, and I do need to be more specific in the issues. But this issue is the ability to change between dark and light and storing that value somewhere. Whereas colour theme is just the colours we choose for the project

**Comment by JeremiahPinto** [comment]
Fixed in #46
